version: "3"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - WATCHPACK_POLLING=true
      - GOOGLE_APPLICATION_CREDENTIALS=./credentials.json